homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 141
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  javascript_version: latest

lovelace:
  mode: yaml

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml #!secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

api:
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
# discovery:
    # ignore:
    # - samsung_tv

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

system_health:

recorder:
  purge_interval: 1
  purge_keep_days: 1
  exclude:
    domains:
      - group
      - device_tracker
      - sensor
      - light
      - media_player
      - scene
      - switch
      - camera
      - switch
      - binary_sensor
      - climate
      - calendar
    entities:
      - sun.sun
      - automation.battery_persistent_notification
      - weather.dark_sky
      
# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - group
      - calendar

#history_graph: !include graphs.yaml

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group
      - calendar
      
# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
#tts:
#  - platform: google

panel_iframe:
  grafana:
    title: Statistik
    url: !secret grafana_url
    icon: mdi:elevation-rise
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_url
# group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
shell_command: !include shell_command.yaml
scene: !include scenes.yaml
switch: !include switch.yaml     
light: !include light.yaml
input_select: !include input_selects.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
# input_text: !include input_text.yaml
# input_number: !include input_number.yaml
sensor: !include senors.yaml
# binary_sensor: !include binary_sensors.yaml
counter: !include counter.yaml
ios: !include push.yaml
homekit: !include homekit.yaml
media_player: !include media_player.yaml
camera: !include camera.yaml

homematic:
  interfaces:
    rf:
      host: 192.168.200.21
    groups:
      host: 192.168.200.21
      port: 9292
      path: /groups
  hosts:
    ccu2:
      host: 192.168.200.21
      username: !secret homematic_user
      password: !secret ccu_password

vacuum:
  - platform: xiaomi_miio
    host: 192.168.200.28
    token: !secret xiaomi_vacuum

device_tracker:
  - platform: fritz
    consider_home: 600

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway

mqtt:
  broker: 192.168.200.50
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: homeassistant  
  password: !secret mqtt_password

influxdb:
  host: 192.168.200.50
  database: home_assistant
  username: home-assistant
  password: !secret influxdb_password
  exclude:
    domains:
      - group
      - automations
      - device_tracker
      - script
      - camera
      - light
      - input_boolean
      - input_select
      - input_text
      - input_datetime
      - input_number
      - scene
      - remote
      - switch
      - media_player
      - light
      - binary_sensor
      - calendar
    entities:
      - sun.sun
      - sensor.time
      - sensor.time_date
      - sensor.date_time
      - weather.dark_sky

hue:
  bridges:
    - host: 192.168.200.52
      allow_unreachable: true
      allow_hue_groups: false

ffmpeg:

remote:
  - platform: harmony
    name: harmony_hub
    host: 192.168.200.55

custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/maykar/custom-lovelace/master/tracker.json

bmw_connected_drive:
 name:
   username: !secret bmw_user
   password: !secret bmw_password
   region: "rest_of_world"

weather:
  - platform: darksky
    api_key: !secret dark_syk

calendar:
  - platform: caldav
    username: !secret next_user
    password: !secret next_password
    url: !secret next_url
    custom_calendars:
      - name: 'Putzfrau'
        calendar: 'Privat'
        search: 'Putzfrau'
      - name: 'Urlaub'
        calendar: 'Privat'
        search: 'Urlaub'
      - name: 'BusinessTrip'
        calendar: 'Arbeit'
        search: 'Business Trip'

# Custom Components
fritzbox_guestwifi:
  username: !secret fritz_user
  password: !secret fritz_password