- platform: harman_kardon_avr
  host: 192.168.200.48
  
# - platform: universal
  # name: Sonos Boxen
  # children:
    # - media_player.schlafzimmer
    # - media_player.bad
  # volume_set:
      # service: media_player.volume_set
      # data_template:
        # entity_id: media_player.bad
        # volume_level: '{{ volume_level }}'
  # attributes:
    # volume_level: media_player.schlafzimmer|volume_level