- platform: template
  switches:
    ###### Tastensperre für Heizung ######
    radiator_bed_room_keylock:
        friendly_name: "Tastensperre"
        value_template: "{{ is_state('sensor.radiator_bed_room_keylock', 'True') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1535747172583
        turn_off:
          - service: script.turn_on
            entity_id: script.1535747298118
        icon_template: >-
          {% if is_state('sensor.radiator_bed_room_keylock', 'True') %}
            mdi:lock-outline
          {% else %}
            mdi:lock-open-outline
          {% endif %}
    radiator_office_keylock:
        friendly_name: "Tastensperre"
        value_template: "{{ is_state('sensor.radiator_office_keylock', 'True') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1535749599600
        turn_off:
          - service: script.turn_on
            entity_id: script.1535749633757
        icon_template: >-
          {% if is_state('sensor.radiator_office_keylock', 'True') %}
            mdi:lock-outline
          {% else %}
            mdi:lock-open-outline
          {% endif %}
    radiator_living_room_keylock:
        friendly_name: "Tastensperre"
        value_template: "{{ is_state('sensor.radiator_living_room_keylock', 'True') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1535749160991
        turn_off:
          - service: script.turn_on
            entity_id: script.1535749518298
        icon_template: >-
          {% if is_state('sensor.radiator_living_room_keylock', 'True') %}
            mdi:lock-outline
          {% else %}
            mdi:lock-open-outline
          {% endif %}
    radiator_bath_keylock:
        friendly_name: "Tastensperre"
        value_template: "{{ is_state('sensor.radiator_bath_keylock', 'True') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538501968289
        turn_off:
          - service: script.turn_on
            entity_id: script.1538502054685
        icon_template: >-
          {% if is_state('sensor.radiator_bath_keylock', 'True') %}
            mdi:lock-outline
          {% else %}
            mdi:lock-open-outline
          {% endif %}
    ###### Fernbedienung ######
    samsung_tv:
        friendly_name: "Samsung UE55J6200"
        value_template: "{{ is_state('device_tracker.ue55j6250', 'home') and is_state('light.steckdose', 'on') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538167144011
        turn_off:
          - service: script.turn_on
            entity_id: script.1538128738934
        icon_template: mdi:television
    avr_151:
        friendly_name: "AVR 151"
        value_template: "{{ is_state('device_tracker.avr151', 'home') and is_state('light.steckdose', 'on') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538167294875
        turn_off:
          - service: script.turn_on
            entity_id: script.1538129107690
        icon_template: mdi:speaker
    telekom_mr_400:
        friendly_name: "Telekom MR 400"
        value_template: "{{ is_state('device_tracker.telekommr400', 'home') and is_state('light.steckdose', 'on')}}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1538167052403
        turn_off:
          - service: script.turn_on
            entity_id: script.1538143115062
        icon_template: mdi:youtube-tv
    ###### Sonos ######
    sonos_group:
        friendly_name: Sonos Gruppe
        value_template: "{{ is_state('sensor.sonos_grouped', 'on') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.1542309376690
        turn_off:
          - service: script.turn_on
            entity_id: script.1542309480271